# Generated by Django 5.0.4 on 2024-05-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetais',
            new_name='UserDetails',
        ),
    ]
