# Generated by Django 5.0.4 on 2024-05-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
