# Generated by Django 5.0.4 on 2024-05-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('productdesc', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=20)),
                ('shipprice', models.FloatField(max_length=10)),
            ],
        ),
    ]
