# Generated by Django 5.0.4 on 2024-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cartdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
