# Generated by Django 5.0.4 on 2024-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cartdetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Netprice', models.FloatField(max_length=12)),
                ('Address', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=15)),
                ('Zip', models.CharField(max_length=10)),
            ],
        ),
    ]
